apiVersion: apps/v1
kind: Deployment
metadata:
  name: mllparty-deployment
  labels:
    app: mllparty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mllparty
  template:
    metadata:
      labels:
        app: mllparty
    spec:
      containers:
        - name: mllparty
          image: $image
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - name: api 
              containerPort: 4000
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: client-api-secret-key-base
                  key: SECRET_KEY_BASE
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DNS_CLUSTER_QUERY
              value: "api-cluster.default.svc.cluster.local"

