name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions: write-all

jobs:
  mixtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hoverkraft-tech/compose-action@v2.2.0
      - name: asdf cache
        id: asdf-cache
        uses: actions/cache@v4
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}
      - uses: asdf-vm/actions/install@179e9530fcd91100e4621bf7e563e7daa8398c52
      - name: Cache Mix
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock', '**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ hashFiles('**/.tool-versions') }}
      - name: install hex
        run: mix local.hex --force
      - run: mix deps.get
      - name: Check warnings
        run: mix compile --warnings-as-errors
      - name: Run tests
        run: mix test
